---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: search-agent-secret
  namespace: search-agent
spec:
  encryptedData:
    SEARCH_AGENT_LLM_API_KEY: <MUST_REGEN>
    SEARCH_AGENT_STAAN_API_KEY: <MUST_REGEN>
  template:
    metadata:
      name: search-agent-secret
      namespace: search-agent
    type: Opaque
